version: "3.3"

services:
  postgres:
    image: postgres:13.1-alpine
    ports:
      - 5433:5432
    env_file:
      - postgres.env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    logging:
        driver: "json-file"
        options:
            max-size: "1g"
            max-file: "3"


  node1:
    build: ./node1
    env_file:
      - chainlink.env
    command: local node -p /chainlink/.password -a /chainlink/.api
    restart: on-failure
    ports:
      - 7788:6688
      - 7979:7979

    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./chainlink-1:/chainlink
    logging:
        driver: "json-file"
        options:
            max-size: "1g"
            max-file: "3"
            
  # node2:
  #   build: ./node2
  #   env_file:
  #     - chainlink.env
  #   command: local node -p /chainlink/.password -a /chainlink/.api
  #   restart: on-failure
  #   ports:
  #     - 7789:6688
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./chainlink-2:/chainlink
  # node3:
  #   build: ./node3
  #   env_file:
  #     - chainlink.env
  #   command: local node -p /chainlink/.password -a /chainlink/.api
  #   restart: on-failure
  #   ports:
  #     - 7790:6688
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./chainlink-3:/chainlink
  # node4:
  #   build: ./node4
  #   env_file:
  #     - chainlink.env
  #   command: local node -p /chainlink/.password -a /chainlink/.api
  #   restart: on-failure
  #   ports:
  #     - 7791:6688
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./chainlink-4:/chainlink
  # bridge-peg-base:
  #   build: ./peg-bridge
  #   command: /initiator pegBase
  #   restart: on-failure
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "1g"
  #       max-file: "3"
  # bridge-peg-usd:
  #   build: ./peg-bridge
  #   command: /initiator pegUsd
  #   restart: on-failure
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "1g"
  #       max-file: "3"
