version: "3.8"

services:
  postgres:
    image: postgres:13.1-alpine
    ports:
      - 5433:5432
    env_file:
      - postgres.env
    volumes:
      - ./db-data:/var/lib/postgresql/data

  node1:
    build: ./node1
    env_file:
      - chainlink.env
    command: local node -p /chainlink-1/.password -a /chainlink-1/.api
    restart: on-failure
    ports:
      - 7788:6688
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./chainlink_data:/chainlink-1
  node2:
    build: ./node2
    env_file:
      - chainlink.env
    command: local node -p /chainlink-2/.password -a /chainlink-2/.api
    restart: on-failure
    ports:
      - 7789:6688
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./chainlink_data:/chainlink-2
  node3:
    build: ./node3
    env_file:
      - chainlink.env
    command: local node -p /chainlink-3/.password -a /chainlink-3/.api
    restart: on-failure
    ports:
      - 7790:6688
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./chainlink_data:/chainlink-3
  node4:
    build: ./node4
    env_file:
      - chainlink.env
    command: local node -p /chainlink-4/.password -a /chainlink-4/.api
    restart: on-failure
    ports:
      - 7791:6688
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./chainlink_data:/chainlink-4
  bridge-peg-base:
    build: ./peg-bridge
    command: /initiator pegBase
    restart: on-failure
  bridge-peg-usd:
    build: ./peg-bridge
    command: /initiator pegUsd
    restart: on-failure
